# Generated by Django 4.1.6 on 2023-02-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrival',
            name='arrival_time',
        ),
        migrations.AlterField(
            model_name='arrival',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
