# Generated by Django 4.1.6 on 2023-02-21 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_arrival_arrival_time_alter_arrival_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrival',
            name='user',
        ),
    ]
